"""create user preferences

Revision ID: 286a1f05e559
Revises: 26b423c62465
Create Date: 2026-10-02 21:27:27.159304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286a1f05e559'
down_revision: Union[str, Sequence[str], None] = '26b423c62465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_preferences_user_id_fkey'), 'user_preferences', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('user_preferences_user_id_fkey'), 'user_preferences', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    # ### end Alembic commands ###
