"""create user preferences

Revision ID: 8dd9747f86df
Revises: 286a1f05e559
Create Date: 2026-10-02 21:52:20.817555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dd9747f86df'
down_revision: Union[str, Sequence[str], None] = '286a1f05e559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('morning_plan_notifications', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_foreign_key(
        "user_preferences_user_id_fkey",
        "user_preferences",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="auth",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'morning_plan_notifications')
    op.drop_constraint(
        "user_preferences_user_id_fkey",
        "user_preferences",
        schema="public",
        type_="foreignkey",
)


    # ### end Alembic commands ###
